language: java
jdk: oraclejdk15

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "fmotot"
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw clean install -B
  # - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar